### ISSUE TITLE
Server error 500 of localhost:8080

### ISSUE THREAD

**Issue by Uei-xian** [ondrejklejch/MT-ComparEval#81]
Hello,
I'm trying to use ComparEval in Windows 7 64-bit system with wampserver (PHP-5.6.35, Apache-2.4.33 and MySQL-5.7.21), but I can't access to localhost: 8080, though it seems that the port has not be occupied. I'm not sure it's relevant with the enviorment or setting, or the server itself.

**Comment by martinpopel** [comment]
I have no experience with MT-ComarEval in Windows, but if you think the problem may be in the port number (8080 may be blocked by your Apache), you can try a different number, e.g. 8081 with `php -S localhost:8081 -t ./www`.

**Comment by Uei-xian** [comment]
Hello again,
The error message is "Nette\InvalidArgumentException Table 'experiments' does not exist."
And here is the code:

    6:     */
    7:    class Experiments {
    8:    
    9:        private $db;
    10:    
    11:        public function __construct( Nette\Database\Context $db ) {
    12:            $this->db = $db;
    13:        }
    14:    
    15:        public function getExperiments() {
    16:            return $this->db->table( 'experiments' )
    17:                ->where( 'visible', 1 );
    18:        }
    19:    
    20:        public function getExperimentById( $experimentId ) {

The argument

    $table | "experiments" (11)

is for line 16.

**Comment by Uei-xian** [comment]
Yes. I run it again and find some problems. They might be the reason of the incorrect inistainstallation:
1. Python 2.7 can only be installed in ```C:\Python27``` or ```C:\Program Files (x86)```, but not ```C:\Program Files``` in the batch file, even I choose it manually; I'm not sure if ```sqlite``` in different folder will affect the function.
2. And I find this error report in the batch file:
```'"C:\Program Flies\sqlite3"' is not recognized as an internal or external command, operable program or batch file.```
I've tried to add this path to system variables, but get the same error.

**Comment by choko** [comment]
I see, the problem is with sqlite3 installation. Initialise the database manually https://github.com/choko/MT-ComparEval/blob/master/bin/win/install.bat#L2? I am sorry, I can't help you much without Windows. 

In the long term, I think it would be much better to Dockerise MT-ComparEval and use Docker on Windows. @martinpopel @lefterav

**Comment by lefterav** [comment]
Hi. Line 2 install.bat presupposes that sqlite has been installed in C:/Program Files . Has it really been installed there? The error you showed shows that there is no sqlite there.

**Comment by Uei-xian** [comment]
Oh I think that is the point... I'll try it later.
