### ISSUE TITLE
Errors to solve

### ISSUE THREAD

**Issue by vince62s** [ondrejklejch/MT-ComparEval#87]
Hi,
I am not a JS master and having a few difficulties to debug.
First there seem to be a new JS version which makes impossible to use variable between quotes.
I replaced by backtick in examples like here: https://github.com/ondrejklejch/MT-ComparEval/blob/master/app/templates/Tasks/list.latte#L20
seems good.

Next: Edit / Save a Task does not work, I am getting a nasty error:

Line 23 of TaskPresenter:
Trying to get property 'id' of non-object
$this->template->experimentId = $this->template->experiment->id;

Cn you help ?

**Comment by ondrejklejch** [comment]
Hi Vincent, thank you for the bug report. I fixed both issues.
